global_costmap:
  global_frame: map
  robot_base_frame: base_footprint
  static_map: true
  update_frequency: 1.0
  publish_frequency: 0.5
  rolling_window: false
  transform_tolerance: 0.5
  plugins:
    - {name: static_layer,   type: 'costmap_2d::StaticLayer'}
    - {name: obstacle_layer, type: 'costmap_2d::VoxelLayer'}
    - {name: inflation_layer, type: 'costmap_2d::InflationLayer'}
  inflation_layer:
    inflation_radius: 0.15
    cost_scaling_factor: 5.0
  obstacle_layer:
    obstacle_range: 2.0
    raytrace_range: 2.0
